base_model: tanamettpk/TC-novid-v1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: tanamettpk/gen_chat
    type: alpaca
  - path: Thaweewat/alpaca-cleaned-52k-th
    type: alpaca
  - path: yahma/alpaca-cleaned
    type: alpaca
  - path: tanamettpk/pipa-rp-en-small
    type: alpaca
  - path: tanamettpk/pipa_roleplay_th
    type: alpaca
  - path: tanamettpk/dialog_generation_v2
    type: alpaca
  - path: tanamettpk/th-cot-k5
    type: alpaca
  - path: tanamettpk/han-instruction-v1.0-reformat
    type: alpaca
  - path: tanamettpk/thaisum-small-instruct-tag
    type: alpaca
  - path: tanamettpk/thaisum-small-instruct-gen
    type: alpaca
  - path: tanamettpk/thaisum-small-instruct
    type: alpaca
  - path: tanamettpk/instruct-qa-thai-combined-small
    type: alpaca
  - path: tanamettpk/toxic-prompt-gen
    type: alpaca
  - path: tanamettpk/story_gen_2k
    type: alpaca
  - path: tanamettpk/nsfw_th_2k
    type: alpaca
  - path: tanamettpk/th-flirty-joke
    type: alpaca
  - path: tanamettpk/inst-nsfw-th-story
    type: alpaca
  - path: tanamettpk/small-inst-th-story
    type: alpaca
dataset_prepared_path: last_run_prepared
val_set_size: 0.002
output_dir: ./qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_linear: true
lora_fan_in_fan_out:
lora_target_modules:
  - gate_proj
  - down_proj
  - up_proj
  - q_proj
  - v_proj
  - k_proj
  - o_proj

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 24
num_epochs: 3
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

eval_sample_packing: False
warmup_steps: 10
evals_per_epoch: 3
eval_table_size:
eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
